### ISSUE TITLE
✨ [Feature] user함수

### ISSUE THREAD

**Issue by Hosung99** [Hosung99/FT_IRC#8]
### Description

Command::user함수를 통해 client객체의 username,servername,realname,hostname변수 설정

### Todo

- [x] password인증이 되어있는지 확인
- [x] 인자가 5개미만이면 클라이언트로 오류 메시지 전송 (close는 안함)
- [x] 이미 인증되어있는지 확인
- [x] is_regist_user true로 set
